# Generated by Django 5.1.3 on 2024-12-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_is_completed_task_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_done',
            new_name='is_completed',
        ),
    ]
